/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smarthomesystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;

/**
 *
 * @author Manel
 */
@Deprecated
public class SetariUsaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    void saveChanges() {
        String changes=App.COMMAND_ANDROID_APPLY+""+App.DOOR_COMMAND;
        changes+=aprindereAutomata.isSelected() ? "1":"0";
        changes+=oprireAutomata.isSelected() ? "1":"0";
        changes+=aplicaSetari.isSelected() ? "1":"0";
        changes+=" ";
        changes+=culoare.getBackground().getRGB();
        
        SmartHomeSystem.getSmartHomeSystem().send(changes);
        
        new Thread() {
            @Override
            public void run() {
        
                if (aprindereAutomata.isSelected() != Settings.AUTOMATIC_LIGHT_ON_DOOR) {
                    aprindereAutomata.setBackground(java.awt.Color.RED);
//flash(aprindereAutomata);
                } else if (oprireAutomata.isSelected() != Settings.AUTOMATIC_LIGHT_OFF_DOOR) {
                    oprireAutomata.setBackground(java.awt.Color.RED);
//flash(oprireAutomata);
                } else if (aplicaSetari.isSelected() != Settings.AUTOMATIC_DOOR_APPLIER) {
                    aplicaSetari.setBackground(java.awt.Color.RED);
//flash(aplicaSetari);
                }
                    
                    

                Settings.AUTOMATIC_DOOR_APPLIER = aplicaSetari.isSelected();
                Settings.AUTOMATIC_LIGHT_OFF_DOOR = oprireAutomata.isSelected();
                Settings.AUTOMATIC_LIGHT_ON_COLOR_DOOR = culoare.getBackground();
                Settings.AUTOMATIC_LIGHT_ON_DOOR = aprindereAutomata.isSelected();
            }
        }.start();

              App.print("Am trimis comenzi " + changes, SetariUsaGUI.class);
    }

    public void receivedResponse() {
        aprindereAutomata.setBackground(SetariUsaGUI.this.getBackground());
        oprireAutomata.setBackground(SetariUsaGUI.this.getBackground());
        aplicaSetari.setBackground(SetariUsaGUI.this.getBackground());
    }

    void flash(JRadioButton button){
        new Thread(){
            @Override
            public void run(){
                button.setBackground(java.awt.Color.RED);
                try {
                    Thread.sleep(300);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SetariUsaGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                button.setBackground(java.awt.Color.GREEN);
                try {
                    Thread.sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SetariUsaGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                button.setBackground(SetariUsaGUI.this.getBackground());
            }
        }.start();
    }
    
    public SetariUsaGUI() {
        initComponents();
        jLabel1.requestFocus();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) d.getWidth() / 2 - getWidth() / 2,
                (int) d.getHeight() / 2 - getHeight() / 2);
        culoare.setContentAreaFilled(false);
        culoare.setOpaque(true);

        aprindereAutomata.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                saveChanges();
            }
        });
        oprireAutomata.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                saveChanges();
            }
        });
        aplicaSetari.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                saveChanges();
            }
        });
    }

    public void onUpdate() {
        aprindereAutomata.setSelected(Settings.AUTOMATIC_LIGHT_ON_DOOR);
        oprireAutomata.setSelected(Settings.AUTOMATIC_LIGHT_OFF_DOOR);
        aplicaSetari.setSelected(Settings.AUTOMATIC_DOOR_APPLIER);
        culoare.setBackground(Settings.AUTOMATIC_LIGHT_ON_COLOR_DOOR);
        App.print("onUpdate",SetariUsaGUI.class);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        aprindereAutomata = new javax.swing.JRadioButton();
        oprireAutomata = new javax.swing.JRadioButton();
        aplicaSetari = new javax.swing.JRadioButton();
        culoare = new javax.swing.JButton();

        setTitle("Setări automatizare ușă");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/icon_usa.png"))); // NOI18N

        aprindereAutomata.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        aprindereAutomata.setText("Aprindere automată la deschiderea ușii");
        aprindereAutomata.setAlignmentX(0.5F);
        aprindereAutomata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        oprireAutomata.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        oprireAutomata.setText("Oprire automată la închiderea ușii");
        oprireAutomata.setAlignmentX(0.5F);
        oprireAutomata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        aplicaSetari.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        aplicaSetari.setText("Aplică setările la conectarea cu telefonul");
        aplicaSetari.setAlignmentX(0.5F);
        aplicaSetari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        culoare.setBackground(new java.awt.Color(255, 255, 255));
        culoare.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        culoare.setText("Culoarea la deschiderea ușii");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aplicaSetari, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                            .addComponent(oprireAutomata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aprindereAutomata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(culoare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(aprindereAutomata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oprireAutomata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aplicaSetari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(culoare)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton aplicaSetari;
    public javax.swing.JRadioButton aprindereAutomata;
    public javax.swing.JButton culoare;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton oprireAutomata;
    // End of variables declaration//GEN-END:variables
}
